"""The knowledge base's converter boundary — deterministic conversion, gated I/O.

This is the **only** module that imports the third-party document converters
(``markitdown``, optionally ``docling``); everything else in the KB deals in the
:class:`ConversionResult` it returns. Design rules (docs/PLAN-4-knowledge.md §D3):

* **Deterministic first.** ``.md`` / ``.txt`` pass through untouched (no library);
  everything else goes to MarkItDown constructed ``enable_plugins=False`` with **no**
  LLM client — plugins, OCR, and image-description are off and are a future explicit
  config, never a silent default. Docling is an optional per-machine escape hatch for
  hard PDFs, behind ``knowledge.pdf_converter``; if not installed it degrades to a
  clear, actionable error rather than an ImportError.
* **Caps before parsers.** Raw bytes over the ingest cap are refused *before* any
  parser touches them — a parser is the attack surface. Zip-container sources also
  have their *uncompressed* size and nesting pre-scanned (a tiny archive can bomb to
  gigabytes), and conversion runs in a killable subprocess so a runaway parser is
  actually cancellable (see :func:`convert_file_sandboxed`).
* **Sanitize on the way in.** A leading YAML front-matter block in converted output
  is stripped: front-matter is a Jarvis-authored artifact, never carried up from
  converter/attacker content (provenance is DB-derived — see ADR-0004).
* **The file leg never touches the network.** URLs go through :func:`fetch_url` /
  :func:`html_to_markdown`, which validate the address (SSRF guard) and re-validate
  every redirect hop. UNC / ``file://`` are rejected before the file leg runs.
"""

from __future__ import annotations

import asyncio
import contextlib
import io
import json
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path

import trafilatura

from jarvis import net
from jarvis.paths import is_sensitive_path

# Source code and project configuration are inert text inputs.  Passing them through avoids
# needlessly invoking an office/document parser for every file in a folder import, while the
# caller's byte cap and path-sensitive checks remain in force.
_PASSTHROUGH_SUFFIXES = frozenset(
    {
        ".md", ".markdown", ".txt", ".text", ".csv", ".json", ".jsonl",
        ".py", ".pyi", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx",
        ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".css", ".scss",
        ".xml", ".sql", ".sh", ".ps1", ".bat", ".cmd",
        ".go", ".rs", ".java", ".kt", ".c", ".h", ".cc", ".cpp", ".hpp",
        ".cs", ".rb", ".php", ".swift", ".vue", ".svelte",
    }
)
# Office/EPUB/ZIP formats are all zip containers — a tiny archive can decompress to
# gigabytes of XML (a "zip bomb"), so their *uncompressed* size is pre-scanned.
_ARCHIVE_SUFFIXES = frozenset({".docx", ".xlsx", ".pptx", ".zip", ".epub"})
_ARCHIVE_EXPANSION_FACTOR = 4  # uncompressed may exceed the raw cap by this factor…
_ARCHIVE_ABSOLUTE_FLOOR = 100_000_000  # …but at least 100 MB (legit big docs expand modestly)
_MAX_ARCHIVE_MEMBERS = 10_000
_FRONT_MATTER = re.compile(r"\A﻿?---\r?\n.*?\r?\n---\r?\n", re.DOTALL)


@dataclass(frozen=True)
class ConversionResult:
    """The deterministic markdown for a source, plus which converter produced it."""

    markdown: str
    title: str | None
    converter: str  # 'passthrough' | 'markitdown' | 'docling' | 'trafilatura'
    converter_version: str


class ConversionError(Exception):
    """A conversion the boundary refuses, or that failed. Message is model-readable."""


def strip_front_matter(md: str) -> str:
    """Remove a leading YAML front-matter block from CONVERTED content.

    Front-matter in the wiki is generated by Jarvis from database state; a block
    that arrives *inside* converted bytes must never be mistaken for provenance."""
    return _FRONT_MATTER.sub("", md, count=1)


# --- file conversion (sync; Task 5 moves the parser call into a subprocess) ---


def check_archive_safety(path: Path, *, max_uncompressed_bytes: int) -> None:
    """Refuse a zip-container source that decompresses to too much, has too many
    members, or nests another archive (all zip-bomb / amplification signatures).

    Reads only the central-directory metadata — no member is extracted — so the
    check itself is cheap and safe. A non-zip file with an archive suffix (corrupt
    or misnamed) is left for the converter to reject."""
    if not zipfile.is_zipfile(path):
        return
    with zipfile.ZipFile(path) as zf:
        infos = zf.infolist()
        if len(infos) > _MAX_ARCHIVE_MEMBERS:
            raise ConversionError(
                f"archive has {len(infos):,} members (> {_MAX_ARCHIVE_MEMBERS:,}) — refused"
            )
        total = sum(zi.file_size for zi in infos)
        if total > max_uncompressed_bytes:
            raise ConversionError(
                f"archive decompresses to {total:,} bytes (> {max_uncompressed_bytes:,}) — "
                "refused as a possible decompression bomb"
            )
        nested = [
            zi.filename for zi in infos if Path(zi.filename).suffix.lower() in _ARCHIVE_SUFFIXES
        ]
        if nested:
            raise ConversionError(f"archive contains nested archives ({nested[:3]}) — refused")


def _precheck(path: Path, max_bytes: int) -> None:
    """Cheap, parser-free guards run before any converter touches the bytes: the
    sensitive-path floor, existence, the raw-size cap, and the archive-bomb scan.
    Shared by :func:`convert_file` (defense in depth inside the worker) and
    :func:`convert_file_sandboxed` (fail fast before spawning a process)."""
    if is_sensitive_path(path):
        raise ConversionError(f"refusing to convert a sensitive path: {path}")
    if not path.is_file():
        raise ConversionError(f"not a file: {path}")
    size = path.stat().st_size
    if size > max_bytes:
        raise ConversionError(
            f"file is {size:,} bytes, over the {max_bytes:,}-byte ingest cap; "
            "raise knowledge.max_ingest_bytes to allow it"
        )
    if path.suffix.lower() in _ARCHIVE_SUFFIXES:
        cap = max(max_bytes * _ARCHIVE_EXPANSION_FACTOR, _ARCHIVE_ABSOLUTE_FLOOR)
        check_archive_safety(path, max_uncompressed_bytes=cap)


def convert_file(
    path: Path, *, max_bytes: int, pdf_converter: str = "markitdown"
) -> ConversionResult:
    """Convert a local file to markdown. ``path`` must already be resolved by the
    caller (and gate-checked); the safety guards are re-applied here as defense in
    depth — the converter must not trust that the gate/pre-check ran on it."""
    _precheck(path, max_bytes)
    suffix = path.suffix.lower()
    if suffix in _PASSTHROUGH_SUFFIXES:
        text = path.read_text(encoding="utf-8", errors="replace")
        return ConversionResult(
            strip_front_matter(text), _title_from_path(path), "passthrough", "1"
        )
    if suffix == ".pdf" and pdf_converter == "docling":
        return _convert_with_docling(path)
    return _convert_with_markitdown(path)


def _title_from_path(path: Path) -> str:
    return path.stem.replace("_", " ").replace("-", " ").strip() or path.name


def _convert_with_markitdown(path: Path) -> ConversionResult:
    md, version = _markitdown()
    result = md.convert(str(path))
    return ConversionResult(
        markdown=strip_front_matter(result.markdown or ""),
        title=(result.title or None) or _title_from_path(path),
        converter="markitdown",
        converter_version=version,
    )


def _convert_with_docling(path: Path) -> ConversionResult:
    try:
        import docling  # type: ignore
        from docling.document_converter import DocumentConverter  # type: ignore
    except ImportError as exc:
        raise ConversionError(
            "knowledge.pdf_converter is 'docling' but docling is not installed. "
            "Install it with `uv sync --extra docling`, or set pdf_converter: markitdown."
        ) from exc
    result = DocumentConverter().convert(str(path))
    return ConversionResult(
        markdown=strip_front_matter(result.document.export_to_markdown()),
        title=_title_from_path(path),
        converter="docling",
        converter_version=getattr(docling, "__version__", "unknown"),
    )


def _markitdown() -> tuple[object, str]:
    """Lazily import MarkItDown, constructed with plugins/LLM OFF. Isolated so a
    test can assert the safe construction and so the heavy import is deferred."""
    import markitdown

    # enable_plugins=False and no llm_client: no third-party plugins, no network
    # image-description calls. enable_builtins defaults on (that's how it reads docx/pdf).
    version = getattr(markitdown, "__version__", "unknown")
    return markitdown.MarkItDown(enable_plugins=False), version


# --- the killable sandbox (Task 5) -------------------------------------------


async def convert_file_sandboxed(
    path: Path, *, max_bytes: int, pdf_converter: str = "markitdown", timeout_seconds: float
) -> ConversionResult:
    """Convert a file in a **separate process** with a hard wall-clock kill.

    ``asyncio.to_thread`` can't cancel a runaway parser — a pathological PDF or a
    decompression bomb keeps burning CPU/RAM after the ``await`` is abandoned. A
    child process makes the timeout real: on deadline the parent kills it. Cheap
    guards run in-parent first (fail fast, and the path never reaches a child for a
    sensitive/oversize/bomb input); the child re-checks as defense in depth."""
    _precheck(path, max_bytes)  # fail fast without spawning
    # Passthrough text has no parser and no attack surface — skip the subprocess.
    if path.suffix.lower() in _PASSTHROUGH_SUFFIXES:
        return convert_file(path, max_bytes=max_bytes, pdf_converter=pdf_converter)
    request = json.dumps(
        {"path": str(path), "max_bytes": max_bytes, "pdf_converter": pdf_converter}
    ).encode()
    proc = await asyncio.create_subprocess_exec(
        sys.executable,
        "-m",
        "jarvis.knowledge.convert_worker",
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(request), timeout=timeout_seconds)
    except TimeoutError as exc:
        proc.kill()
        with contextlib.suppress(ProcessLookupError):
            await proc.wait()
        raise ConversionError(
            f"conversion of {path.name} exceeded {timeout_seconds:g}s and was terminated"
        ) from exc
    if proc.returncode != 0:
        detail = stderr.decode("utf-8", errors="replace").strip()[-500:]
        raise ConversionError(f"converter subprocess crashed: {detail or 'no output'}")
    try:
        payload = json.loads(stdout.decode("utf-8", errors="replace"))
    except json.JSONDecodeError as exc:
        raise ConversionError(f"converter subprocess produced no valid result: {exc}") from exc
    if not payload.get("ok"):
        raise ConversionError(payload.get("error", "unknown conversion error"))
    return ConversionResult(
        markdown=payload["markdown"],
        title=payload["title"],
        converter=payload["converter"],
        converter_version=payload["converter_version"],
    )


# --- web conversion (async; SSRF-guarded fetch, deterministic extraction) -----


async def fetch_url(url: str, *, timeout_seconds: float) -> tuple[bytes, str | None]:
    """Fetch a URL's raw bytes (the immutable artifact) + content-type, SSRF-guarded
    on the initial URL and every redirect hop. Raises :class:`ConversionError` on an
    unsafe address."""
    try:
        resp = await net.safe_get(url, timeout_seconds=timeout_seconds)
    except ValueError as exc:  # SSRF rejection / redirect loop
        raise ConversionError(str(exc)) from exc
    return resp.content, resp.headers.get("content-type")


def html_to_markdown(html: str, *, url: str | None = None) -> ConversionResult:
    """Convert fetched HTML to markdown: trafilatura (article extraction) first, and
    MarkItDown on the raw HTML as a fallback for non-article pages."""
    text = trafilatura.extract(
        html, output_format="markdown", include_links=True, include_tables=True, url=url
    )
    if text and text.strip():
        version = getattr(trafilatura, "__version__", "unknown")
        return ConversionResult(
            strip_front_matter(text), _title_from_html(html), "trafilatura", version
        )
    md, version = _markitdown()
    from markitdown import StreamInfo

    result = md.convert_stream(
        io.BytesIO(html.encode("utf-8", errors="replace")),
        stream_info=StreamInfo(extension=".html", mimetype="text/html", url=url),
    )
    return ConversionResult(
        markdown=strip_front_matter(result.markdown or ""),
        title=(result.title or None) or _title_from_html(html),
        converter="markitdown",
        converter_version=version,
    )


def _title_from_html(html: str) -> str | None:
    match = re.search(r"<title[^>]*>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else None
